### ISSUE TITLE
Clarification on rpcworkqueue value and Dogecoin node settings

### ISSUE THREAD

**Issue by christiangrieger** [DogihubMain/hub_indexer_public#1]
Hi everyone,

I have a couple of questions about setting up my Dogecoin node. I'd appreciate some help:

**rpcworkqueue Value:** 

Should the rpcworkqueue value match rpcPoolSize?

**Optimal rpcworkqueue Value: What's the best rpcworkqueue value for my server specs:** 

CPU: Intel Xeon E5 1650
RAM: 64 GB
Disks: 2 x 1 TB SSD
OS: Debian 11 (Bullseye)?

**Indexer API and Database Structure:** 

Does the indexer have API endpoints, or do I need to create custom ones based on Redis? 
Also, where can I find info about the database structure?

Any help is appreciated!

Thanks!

**Comment by Dogihub** [comment]
Hi @ChristianGrieger 

Yes it is better if the the node "rpcworkqueue" parameter match with the "rpcPoolSize" parameter from the indexer.
The most important is that rpcPoolSize must be equal or inferior as rpcworkqueue to avoid bottleneck.

For your context a value of 100 could be great

For now the indexer is not provided with an API.
You can create your own over the redis database. All indexes are designed to be relevant for balances
You can find the redis keys used in the RedisKeys file over here : https://github.com/DogihubMain/hub_indexer_public/blob/main/DogiHubIndexer/Configuration/RedisKeys.cs

Hope its help

**Comment by christiangrieger** [comment]
Thank you.
