### ISSUE TITLE
Redis is now ready to exit, bye bye...

### ISSUE THREAD

**Issue by christiangrieger** [DogihubMain/hub_indexer_public#2]
I tried to create the docker for redis with the delivered file and get this error. Any idea how to check the error and get the redis running?

```
root@sd-XXX:~/apps/doginals_hub_indexer/indexer# docker logs --timestamps indexer-redis-1
2024-03-01T06:46:33.826833001Z 1:signal-handler (1709275593) Received SIGTERM scheduling shutdown...
2024-03-01T06:46:33.956956662Z 1:M 01 Mar 2024 06:46:33.956 # Redis is now ready to exit, bye bye...
```

**Comment by Dogihub** [comment]
Hi @ChristianGrieger 

Try with this one please : 

```
version: "3.1"

services:
  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --dir /data --maxmemory-policy noeviction --tracking-table-max-keys 100000 --save 20 1 --loglevel warning --requirepass yourpass
    volumes:
      - ./redis_data:/data

volumes:
  redis:
    driver: local
```

**Comment by christiangrieger** [comment]
Sadly I get the same result.

**Comment by Dogihub** [comment]
check if the 6379 port is not already in use in your host
try to delete your local redis_data and let the docker create it again

which command are you using to run the docker compose ?

feel free to use the redis config you want, it is just an example

**Comment by toregua** [comment]
no news for 2 weeks i close the ticket
